import type { Metadata } from "next";
import {Inter, Rubik} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "../providers";
import {cn} from "@/lib/utils";
import { Rubik as FontSans } from "next/font/google"
import {ThemeProvider} from "next-themes";
import {SessionContext, SessionProvider} from "next-auth/react";
import {Toaster} from "@/components/ui/toaster";

  const inter = Rubik({ subsets: ["latin"] });

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "GetJob - сайт по поиску работы",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable)}>
          <Providers>
              <Navbar />
              {children}
              <Toaster />
          </Providers>
      </body>
    </html>
  );
}
