import type { Metadata } from "next";
import {Inter, Rubik} from "next/font/google";
import "./globals.css";
import providers from "./providers";
import Navbar from "@/components/Navbar";
import Providers from "./providers";

  const inter = Rubik({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body className={inter.className}>
          <>
              <Providers>
                  <Navbar />
                  {children}
              </Providers>
          </>
      </body>
    </html>
  );
}
