import type { Metadata } from "next";
import {Inter, Rubik} from "next/font/google";
import "./globals.css";
import providers from "../components/providers";
import Navbar from "@/components/Navbar";
import Providers from "../components/providers";
import {cn} from "@/lib/utils";
import { Rubik as FontSans } from "next/font/google"
import {ThemeProvider} from "next-themes";

  const inter = Rubik({ subsets: ["latin"] });

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable)}>
          <>
              <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                  >
                  <Navbar />
                  {children}
              </ThemeProvider>
          </>
      </body>
    </html>
  );
}
